from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol

from backend.domain.git.types import CommitSummary, DiffSummary, GitRef, WorktreeStatus


ProgressCallback = Callable[[dict[str, Any]], None]


class GitProviderPort(Protocol):
    def discover_repositories(self, roots: list[Path]) -> list[dict[str, Any]]: ...

    def clone(self, *, remote_url: str, destination: Path, progress: ProgressCallback | None = None) -> Path: ...

    def fetch(self, *, repo_path: Path, progress: ProgressCallback | None = None) -> dict[str, Any]: ...

    def pull(self, *, repo_path: Path, progress: ProgressCallback | None = None) -> dict[str, Any]: ...

    def list_refs(self, *, repo_path: Path) -> list[GitRef]: ...

    def create_branch(self, *, repo_path: Path, branch_name: str, start_point: str | None = None) -> GitRef: ...

    def checkout(self, *, repo_path: Path, ref_name: str) -> dict[str, Any]: ...

    def delete_branch(self, *, repo_path: Path, branch_name: str) -> None: ...

    def commit(self, *, repo_path: Path, message: str, paths: list[str] | None = None) -> CommitSummary: ...

    def status(self, *, repo_path: Path) -> WorktreeStatus: ...

    def diff_summary(self, *, repo_path: Path, base_ref: str, head_ref: str, path_filter: str | None = None) -> DiffSummary: ...

    def compare_commits(self, *, repo_path: Path, base_ref: str, head_ref: str, limit: int = 20) -> list[CommitSummary]: ...

    def reset_soft(self, *, repo_path: Path, commit_sha: str) -> None: ...
